### ISSUE TITLE
Feature request: Acid rain damage crops

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#27]
It would be nice if acid rain damaged crops. Configuration might be something like:
```
Acidrain:
...
  # Use if you want acid rain to damage drops. Chance is the percent of crop that will be affected per storm. It will typically be a small number.
  CropDamage:
    Enabled: true
    Chance: 1
...
```
