### ISSUE TITLE
Acidrain console/log message error

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#28]
Spigot 1.13.2 latest
PWP 2.1.0

In my set-up, acidrain is started by a skript that eventually executes
```
essentials:weather world_yellowdog storm %duration%
```
in this case 167. Console/log displays:
```
[18:08:07 INFO]: [PyroWeatherPro] Acidrain has stopped in world_yellowdog.
[18:31:04 INFO]: You set the weather to storm in world_yellowdog for 167 seconds.
[18:31:04 INFO]: [PyroWeatherPro] Acidrain has started in world_yellowdog for 1000000000 seconds.
[18:33:51 INFO]: [PyroWeatherPro] Acidrain has stopped in world_yellowdog.
```
but the storm actually stops as expected. The skript does not explicitly stop the storm, so the reported billion is erroneous.

Business portion of _config.yml_
```
Console:
  #Notifications will display in console when a storm starts / stop. (bear in mind it will log twice if normal acidrain messages are active.)
  Notifications:
    Acidrain:
      Enabled: true
      StartMessage: '[PyroWeatherPro] Acidrain has started in %world% for %time% seconds.'
      StopMessage: '[PyroWeatherPro] Acidrain has stopped in %world%.'
    GammaRay:
      Enabled: false
      StartMessage: '[PyroWeatherPro] A Gamma Ray Burst has been detected in %world% and will impact in %time% seconds.'
      HitMessage: '[PyroWeatherPro] The Gamma Ray Burst has Hit.'
      FinishMessage: '[PyroWeatherPro] The Gamma Ray Burst effects have subsided.'


#================================================================================================================

#Acid rain information
Acidrain:
  Enabled: true
  #This is for the GriefPrevention plugin. Settings this to false will make it so players do not take damage in claims.
  DisabledInClaims: false
  #Worlds in which acidrain is enabled in
  Worlds:
    - 'world_yellowdog'
  #World Guard support. Put your region names which you want acid rain to be disabled. It will still rain here but will not deal damage or give effects to players.
  DisabledRegions:
    - 'none'
  #Chance of the acidrain starting and how long it will last.
  Chances:
    ChanceToStart: 100
    ChanceTimer: 300
  #General storm information, how long it lasts and how much damage it deals including the interval of the damage.
  StormInformation:
    StormTime: 180
    DamageInterval: 1
    BaseDamage: 1
  #Some options which you can enable / disable while acidrain is active.
  Other:
    DealKnockback: false
    #Will make all the water Acidic
    MakeWaterAcidic:
      Enabled: true
      #Always active regardless of weather
      AlwaysActive: true
      #Makes it so it is ONLY active during rain or a storm
      AlwaysActiveInRain: false
      #Damage interval of the Acidic water
      DamageInterval: 1
      #Acidic Water will only work above this Y level
      MinimumAcidicWaterYLevel: 50
    #All rain will be acidic
    AllStormsAcid: true
    #Will use title messages when the storm starts
    TitleMessageNotfications: false
    #Will make it so the Acidrain cannot kill the player
    CantKill: false
    #This will make it so messages are displayed when acidrain starts / stops
    DisplayStartStopMessages: false
 ```

Have I missed something or made a configuration error?
