### ISSUE TITLE
Invisible/silent rain?

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#43]
Spigot 1.13.2 final
PWP 3.3.0

I am testing Acidrain configuration. I am in an enabled biome (FOREST). I see warning messages in-game and on log/console, and I see log/console messages that rain starts and stops. Potion effects are generated on the players
```
    Effects:
      - 'Confusion'
      - 'Hunger'
      - 'Slow'
      - 'Weakness'
```
but there are no raindrops or storm sounds. I must be doing something wrong, but I don't see what. Rain can be started normally with **essentials:storm storm**.

config.yml (sans comments):
```
Config-Version: 3.3.0
GeneralSettings:
  DisableWeatherWorlds:
    - 'none'
  ChangeWorld:
    InvulnerabilityTime: 10
  HideSpigotURL: true
  VersionChecker: false
Console:
  Notifications:
    Acidrain:
      Enabled: true
      StartMessage: '[PyroWeatherPro] Acidrain started in %world%.'
      StopMessage: '[PyroWeatherPro] Acidrain stopped in %world%.'
    GammaRay:
      Enabled: false
      StartMessage: '[PyroWeatherPro] A Gamma Ray Burst has been detected in %world% and will impact in %time% seconds.'
      HitMessage: '[PyroWeatherPro] The Gamma Ray Burst has Hit.'
      FinishMessage: '[PyroWeatherPro] The Gamma Ray Burst effects have subsided.'
StormTimer:
  Timer: 153
  Chances:
    Acidrain: 50.0 
    Gammaray: 0.0
Acidrain:
  Enabled: true
  UseCustomMobs: false
  DisabledInClaims: false
  Worlds:
    - 'world_yellowdog'
  DisabledRegions:
    - 'none'
  StormInformation:
    StormTime:     
      Median: 180    
      RandomDuration:
        Enabled: true
        UpperBound: 299
        LowerBound: 59
    WarningTime:
      Enabled: true
      Duration: 30
    DamageInterval: 1
    BaseDamage: 1
  Other:
    Armor:
      Enabled: true
      DamageMultipliers:
        Leather:
          Helmet: 0.90
          Chestplate: 0.95
          Leggings: 0.95
          Boots: 0.99       
        Iron:
          Helmet: 0.75
          Chestplate: 0.85
          Leggings: 0.90
          Boots: 0.95        
        ChainMail:
          Helmet: 0.80
          Chestplate: 0.80
          Leggings: 0.90
          Boots: 0.95        
        Gold:
          Helmet: 0.60
          Chestplate: 0.75
          Leggings: 0.90
          Boots: 0.95        
        Diamond:
          Helmet: 0.50
          Chestplate: 0.75
          Leggings: 0.90
          Boots: 0.95
        TurtleHelmet: 0.25
    DealKnockback: false
    AllowedGamemodes:
      - 'SURVIVAL'
      - 'ADVENTURE'
    MakeWaterAcidic:
      Enabled: true
      AlwaysActive: true
      AlwaysActiveInRain: false
      DamageInterval: 1
      MinimumAcidicWaterYLevel: 50
    AllStormsAcid: true
    TitleMessageNotfications: false
    CantKill: false
    DisplayStartStopMessages: false
  DisabledBiomes:
    - 'NETHER'
    - 'BADLANDS'
    - 'DESERT'
    - 'DESERT HILLS'
    - 'DESERT LAKES'
    - 'ERODED BADLANDS'
    - 'PLATEAU'
    - 'MODIFIED BADLANDS PLATEAU'
    - 'MODIFIED PLATEAU'
    - 'SAVANNA'
    - 'SHATTERED SAVANNA'
    - 'SHATTERED SAVANNA PLATEAU'
    - 'WOODED BADLANDS PLATEAU'
  PotionEffects:
    Enabled: true
    Chances:
      Chance: 90
      ChanceTimer: 30
    Effects:
      - 'Confusion'
      - 'Hunger'
      - 'Slow'
      - 'Weakness'
    EffectDuration: 5
    EffectPotentcy: 1
AcidicMobs:
  TypesToAcidify:
    - 'ZOMBIE'
    - 'SKELETON' 
    - 'SPIDER'
    - 'WITCH'
    - 'CREEPER'
  Attributes:
    Health: 1.25
    Damage: 1.25  
    MovementSpeed: 1.1
    KnockbackResistance: 1.1
  Other:
    AlwaysDisplayCustomName: true  
  PoisonDamage:
    Time: 2
  OnDeath:
    ExperienceToDrop: 1.05    
GammaRay:
  Enabled: false
  UseCustomMobs: false
  Worlds:
    - 'world_yellowdog'
  DisabledInClaims: false
  DisabledRegions:
    - 'exampleregionname'
    - 'exampleregionname2'
  DisabledBiomes:
    - 'NETHER'
  StormInformation:
    WarningTime: 30
    ScorchedMobsTime: 600 
  Chances:
    ChanceToStart: 10
    ChanceTimer: 600   
  Other:
    DisplayStartStopMessages: true
    DisplayHitMessage: true
    HitSound: 'BLOCK_PORTAL_TRAVEL'
    Armor:
      Enabled: true
      DamageMultipliers:
        Leather:
          Helmet: 0.95
          Chestplate: 0.95
          Leggings: 0.95
          Boots: 0.95       
        Iron:
          Helmet: 0.90
          Chestplate: 0.90
          Leggings: 0.90
          Boots: 0.90        
        ChainMail:
          Helmet: 0.90
          Chestplate: 0.90
          Leggings: 0.90
          Boots: 0.90        
        Gold:
          Helmet: 0.80
          Chestplate: 0.80
          Leggings: 0.80
          Boots: 0.80        
        Diamond:
          Helmet: 0.70
          Chestplate: 0.70
          Leggings: 0.70
          Boots: 0.70
        TurtleHelmet: 0.4
  Damage:
    BaseDamage: 10
    BurnTime: 15
  PotionEffects:
    Enabled: true
    ChanceToApplyEffect: 50
    AmountToApply: 2
    Potency: 3
    Duration: 15
    Effects:
      - 'Blindness'
      - 'Hunger'
      - 'Slow'
ScorchedMobs:
  Enabled: false
  TypesToScorch:
    - 'ZOMBIE'
    - 'SKELETON' 
    - 'SPIDER'
    - 'WITCH'
    - 'CREEPER'
  Attributes:
    Health: 1.25
    Damage: 1.25  
  Other:
    AlwaysDisplayCustomName: true  
  FireDamage:
    BurnTime: 2
  OnDeath:
    ExperienceToDrop: 1.05
Temperature:
  Enabled: false
  Worlds:
    - 'world_none'
  BaseValues:
    BaseTemperature: 15
    TemperatureRangeDifference: 5
    TemperatureDiffernceChangeTime: 300
  Thresholds:
    TooHotTemperature: 40
    TooColdTemperature: 0
  TooHot:
    IncrementalSideEffects:
      Enabled: true
      AmountBeforeIncrease: 8
    ChanceTimer: 10
    BaseEffects:
      Effects:
        - SLOW
        - SLOW_DIGGING
      EffectDuration: 5
      EffectPotency: 1
      ChanceToApply: 15
  TooCold:
    IncrementalSideEffects:
      Enabled: true
      AmountBeforeIncrease: 8
    ChanceTimer: 10
    BaseEffects:
      Effects:
        - SLOW
        - SLOW_DIGGING
        - HUNGER  
      EffectDuration: 5
      EffectPotency: 1
      ChanceToApply: 15   
  General:
    BiomeTemperatures: true
    ActionBarTimer: 3.5
    TemperatureChanges:
      PlayerArmor: true
      InWater:
        Enabled: true
        Difference: -10
      InLava:
        Enabled: true
        Difference: 20
      Altitude:
        Enabled: true
        DistanceBetweenChange: 10
        ChangeDifference: 1
        MedianDistance: 70
      HoldingItems:
        Enabled: true
        Items:
          1:
            Itemname: TORCH
            Difference: 5
          2:
            Itemname: LAVA_BUCKET
            Difference: 20
          3:
            Itemname: BLAZE_ROD
            Difference: 10
          4:
            Itemname: WATER_BUCKET
            Difference: -8
          5:
            Itemname: ICE
            Difference: -20        
      OnFire:
        Enabled: true
        Difference: 20
      PlayerBiome: true
    Biomes:
      1:
        BiomeName: DESERT
        TemperatureChange: 20
      2:
        BiomeName: SWAMP
        TemperatureChange: 7
      3:
        BiomeName: ICE_PLAINS
        TemperatureChange: -40
```
